image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - java -jar aapp-ibank-build-for-testers.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true
